using System;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using DataverseProcessMapper.Models;

namespace DataverseProcessMapper.Exporters
{
    /// <summary>
    /// Exports a process map to a self-contained HTML file: the diagram is
    /// embedded as a high-resolution PNG (base64) and is accompanied by a
    /// metadata header and a readable step/connector table.
    /// </summary>
    public static class HtmlExporter
    {
        public static void Save(ProcessMap map, string path)
        {
            string pngBase64;
            using (var bmp = ProcessMapBuilder.RenderToBitmap(map, 2f))
            using (var ms = new MemoryStream())
            {
                bmp.Save(ms, ImageFormat.Png);
                pngBase64 = Convert.ToBase64String(ms.ToArray());
            }

            File.WriteAllText(path, BuildHtml(map, pngBase64), Encoding.UTF8);
        }

        private static string BuildHtml(ProcessMap map, string pngBase64)
        {
            var item = map.Source;
            var sb = new StringBuilder();
            sb.AppendLine("<!DOCTYPE html>");
            sb.AppendLine("<html lang=\"en\"><head>");
            sb.AppendLine("<meta charset=\"utf-8\">");
            sb.AppendLine("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
            sb.AppendLine($"<title>{E(map.Graph.Title)} – Process Map</title>");
            sb.AppendLine("<style>");
            sb.AppendLine(Css());
            sb.AppendLine("</style></head><body>");

            sb.AppendLine("<div class=\"wrap\">");
            sb.AppendLine($"<h1>{E(map.Graph.Title)}</h1>");
            sb.AppendLine("<table class=\"meta\"><tbody>");
            Meta(sb, "Type", item?.CategoryLabel);
            Meta(sb, "Primary table", string.IsNullOrEmpty(item?.PrimaryEntity) ? "—" : item.PrimaryEntity);
            Meta(sb, "Status", item?.StateLabel);
            Meta(sb, "Steps", map.Graph.Nodes.Count.ToString());
            Meta(sb, "Generated", DateTime.Now.ToString("yyyy-MM-dd HH:mm"));
            sb.AppendLine("</tbody></table>");

            sb.AppendLine("<div class=\"diagram\">");
            sb.AppendLine($"<img alt=\"Process map for {E(map.Graph.Title)}\" src=\"data:image/png;base64,{pngBase64}\">");
            sb.AppendLine("</div>");

            // Step list
            sb.AppendLine("<h2>Steps</h2>");
            sb.AppendLine("<table class=\"steps\"><thead><tr><th>#</th><th>Step</th><th>Kind</th><th>Detail</th></tr></thead><tbody>");
            int i = 1;
            foreach (var n in map.Graph.Nodes)
            {
                sb.AppendLine("<tr>" +
                    $"<td class=\"num\">{i++}</td>" +
                    $"<td><span class=\"dot {KindClass(n.Kind)}\"></span>{E(n.Label.Replace("\n", " "))}</td>" +
                    $"<td>{E(n.Kind.ToString())}</td>" +
                    $"<td>{E(n.Subtitle)}</td></tr>");
            }
            sb.AppendLine("</tbody></table>");

            // Connectors with labels
            var labeled = map.Graph.Edges.Where(e => !string.IsNullOrEmpty(e.Label)).ToList();
            if (labeled.Count > 0)
            {
                sb.AppendLine("<h2>Branches</h2>");
                sb.AppendLine("<table class=\"steps\"><thead><tr><th>From</th><th>Condition</th><th>To</th></tr></thead><tbody>");
                foreach (var e in labeled)
                {
                    var from = map.Graph[e.FromId];
                    var to = map.Graph[e.ToId];
                    sb.AppendLine("<tr>" +
                        $"<td>{E(from?.Label.Replace("\n", " "))}</td>" +
                        $"<td><b>{E(e.Label)}</b></td>" +
                        $"<td>{E(to?.Label.Replace("\n", " "))}</td></tr>");
                }
                sb.AppendLine("</tbody></table>");
            }

            sb.AppendLine("<p class=\"footer\">Generated by Dataverse Process Mapper for XrmToolBox.</p>");
            sb.AppendLine("</div></body></html>");
            return sb.ToString();
        }

        private static void Meta(StringBuilder sb, string label, string value)
            => sb.AppendLine($"<tr><th>{E(label)}</th><td>{E(value)}</td></tr>");

        private static string KindClass(NodeKind kind)
        {
            switch (kind)
            {
                case NodeKind.Trigger: return "k-trigger";
                case NodeKind.Start: return "k-start";
                case NodeKind.End: return "k-end";
                case NodeKind.Condition:
                case NodeKind.Switch: return "k-cond";
                case NodeKind.Loop: return "k-loop";
                case NodeKind.Terminate: return "k-term";
                default: return "k-action";
            }
        }

        private static string E(string s) => string.IsNullOrEmpty(s) ? "" : WebUtility.HtmlEncode(s);

        private static string Css()
        {
            return @"
:root { --fg:#1f2936; --muted:#6b7280; --line:#e5e7eb; }
* { box-sizing: border-box; }
body { margin:0; background:#f3f4f6; color:var(--fg);
       font-family:'Segoe UI',Roboto,Helvetica,Arial,sans-serif; }
.wrap { max-width:1100px; margin:24px auto; background:#fff; padding:28px 34px;
        border-radius:12px; box-shadow:0 1px 4px rgba(0,0,0,.08); }
h1 { margin:0 0 4px; font-size:24px; }
h2 { margin:28px 0 8px; font-size:16px; border-bottom:1px solid var(--line); padding-bottom:6px; }
table.meta { border-collapse:collapse; margin:10px 0 4px; }
table.meta th { text-align:left; color:var(--muted); font-weight:600; padding:2px 16px 2px 0; }
table.meta td { padding:2px 0; }
.diagram { margin:18px 0; overflow:auto; border:1px solid var(--line); border-radius:8px; background:#fff; padding:10px; }
.diagram img { max-width:100%; height:auto; display:block; }
table.steps { width:100%; border-collapse:collapse; font-size:14px; }
table.steps th, table.steps td { text-align:left; padding:7px 10px; border-bottom:1px solid var(--line); vertical-align:top; }
table.steps thead th { color:var(--muted); font-size:12px; text-transform:uppercase; letter-spacing:.04em; }
td.num { color:var(--muted); width:34px; }
.dot { display:inline-block; width:9px; height:9px; border-radius:50%; margin-right:8px; vertical-align:middle; }
.k-trigger{background:#00897b;} .k-start{background:#388e3c;} .k-end{background:#616161;}
.k-cond{background:#f59f00;} .k-loop{background:#8e24aa;} .k-term{background:#c62828;} .k-action{background:#1976d2;}
.footer { margin-top:24px; color:var(--muted); font-size:12px; }
";
        }
    }
}
