using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using DataverseProcessMapper.Layout;
using DataverseProcessMapper.Models;

namespace DataverseProcessMapper.Exporters
{
    /// <summary>
    /// Writes the process as structured Markdown for use as an AI knowledge
    /// source (Copilot Studio, or any retrieval system).
    ///
    /// A diagram is close to the worst possible artifact for retrieval: the
    /// connectors are geometry, so extracting text from a PDF or image yields a
    /// bag of step names with no relationships. This export states the
    /// relationships as sentences instead — what a step runs after, what it
    /// branches into, what is nested inside it, and which steps run at the same
    /// time — and uses headings so a chunker inherits the real hierarchy.
    /// </summary>
    public static class MarkdownExporter
    {
        private const int MaxHeadingDepth = 6;

        public static void Save(ProcessMap map, string path)
            => File.WriteAllText(path, Build(map), new UTF8Encoding(false));

        public static string Build(ProcessMap map)
        {
            // The full graph, so the export never depends on what is collapsed
            // in the UI; blocks are recomputed over it for the same reason.
            var graph = map.Graph;
            var blocks = ParallelBlockDetector.Detect(graph);

            var sb = new StringBuilder();
            AppendHeader(sb, map, graph);
            AppendOverview(sb, graph, blocks);

            sb.AppendLine("## Steps");
            sb.AppendLine();
            AppendSteps(sb, graph, null, 3);

            sb.AppendLine("---");
            sb.AppendLine();
            sb.AppendLine("Generated by Dataverse Process Mapper for XrmToolBox.");
            return sb.ToString();
        }

        private static void AppendHeader(StringBuilder sb, ProcessMap map, ProcessGraph graph)
        {
            var item = map.Source;
            sb.AppendLine("# " + Clean(graph.Title));
            sb.AppendLine();

            // Stated as sentences rather than a table: retrieval matches prose
            // far more reliably than table cells.
            var facts = new List<string>();
            if (item != null)
            {
                facts.Add("a " + item.CategoryLabel);
                if (!string.IsNullOrEmpty(item.PrimaryEntity))
                    facts.Add("running against the `" + item.PrimaryEntity + "` table");
                facts.Add("currently " + item.StateLabel.ToLowerInvariant());
            }
            facts.Add("made up of " + graph.Nodes.Count + " steps");

            sb.AppendLine("**" + Clean(graph.Title) + "** is " + string.Join(", ", facts) + ".");
            sb.AppendLine();
            if (item?.ModifiedOn != null)
                sb.AppendLine("Last modified " + item.ModifiedOn.Value.ToString("yyyy-MM-dd") + ". " +
                              "Documented " + DateTime.Now.ToString("yyyy-MM-dd") + ".");
            else
                sb.AppendLine("Documented " + DateTime.Now.ToString("yyyy-MM-dd") + ".");
            sb.AppendLine();
        }

        private static void AppendOverview(StringBuilder sb, ProcessGraph graph, List<ParallelBlock> blocks)
        {
            sb.AppendLine("## Overview");
            sb.AppendLine();

            var trigger = graph.Nodes.FirstOrDefault(n => n.Kind == NodeKind.Trigger);
            if (trigger != null)
            {
                sb.AppendLine("This process is triggered by **" + Clean(trigger.Label) + "**" +
                              (string.IsNullOrEmpty(trigger.Subtitle) ? "" : " (" + Clean(trigger.Subtitle) + ")") + ".");
                sb.AppendLine();
            }

            var counts = graph.Nodes
                .GroupBy(n => n.Kind)
                .OrderByDescending(g => g.Count())
                .Select(g => g.Count() + " " + Plural(g.Key, g.Count()))
                .ToList();
            sb.AppendLine("It contains " + JoinWithAnd(counts) + ".");
            sb.AppendLine();

            var empties = graph.Nodes.Count(n => n.Kind == NodeKind.Empty);
            if (empties > 0)
            {
                sb.AppendLine(empties + " branch" + (empties == 1 ? "" : "es") +
                              " are defined but contain no actions.");
                sb.AppendLine();
            }

            if (blocks.Count > 0)
            {
                sb.AppendLine("### Steps that run at the same time");
                sb.AppendLine();
                foreach (var b in blocks)
                {
                    var entry = graph[b.EntryId];
                    var exit = graph[b.ExitId];
                    sb.AppendLine("After **" + Clean(entry?.Label) + "**, " + b.BranchCount +
                                  " branches run at the same time. All of them must finish before **" +
                                  Clean(exit?.Label) + "** runs:");
                    sb.AppendLine();
                    foreach (var branch in b.Branches)
                        sb.AppendLine("- " + string.Join(" then ",
                            branch.Select(id => Clean(graph[id]?.Label))));
                    sb.AppendLine();
                }
            }
        }

        /// <summary>Emits the children of <paramref name="parentId"/> (null = top level).</summary>
        private static void AppendSteps(StringBuilder sb, ProcessGraph graph, string parentId, int depth)
        {
            int heading = Math.Min(depth, MaxHeadingDepth);

            foreach (var node in graph.Nodes.Where(n => n.ParentId == parentId))
            {
                sb.AppendLine(new string('#', heading) + " " + Clean(node.Label));
                sb.AppendLine();

                var kind = node.Kind.ToString();
                sb.AppendLine("*" + kind + (string.IsNullOrEmpty(node.Subtitle)
                    ? "" : " · " + Clean(node.Subtitle)) + "*");
                sb.AppendLine();

                AppendRelationships(sb, graph, node);
                AppendDetails(sb, node);

                var children = graph.Nodes.Where(c => c.ParentId == node.Id).ToList();
                if (children.Count > 0)
                {
                    sb.AppendLine("Contains " + children.Count + " step" +
                                  (children.Count == 1 ? "" : "s") + ", described below.");
                    sb.AppendLine();
                    AppendSteps(sb, graph, node.Id, depth + 1);
                }
            }
        }

        /// <summary>
        /// The part a diagram cannot give a retrieval system: which step this one
        /// follows, and where each labelled branch leads.
        /// </summary>
        private static void AppendRelationships(StringBuilder sb, ProcessGraph graph, ProcessNode node)
        {
            var lines = new List<string>();

            var incoming = graph.Edges
                .Where(e => e.ToId == node.Id && !e.IsBack && graph[e.FromId]?.Id != node.ParentId)
                .Select(e => Clean(graph[e.FromId]?.Label))
                .Where(l => !string.IsNullOrEmpty(l))
                .Distinct()
                .ToList();
            if (incoming.Count > 0)
                lines.Add("Runs after " + JoinWithAnd(incoming.Select(l => "**" + l + "**").ToList()) + ".");

            foreach (var e in graph.Edges.Where(e => e.FromId == node.Id && !string.IsNullOrEmpty(e.Label)))
            {
                var target = Clean(graph[e.ToId]?.Label);
                if (!string.IsNullOrEmpty(target))
                    lines.Add("If **" + Clean(e.Label) + "**, continues to **" + target + "**.");
            }

            if (lines.Count == 0) return;
            foreach (var l in lines) sb.AppendLine(l);
            sb.AppendLine();
        }

        private static void AppendDetails(StringBuilder sb, ProcessNode node)
        {
            if (node.Details == null || node.Details.Count == 0) return;

            // "Runs after" is already stated as a sentence above, with the step
            // names in bold; repeating it as a bullet is noise in the index.
            var details = node.Details
                .Where(d => !string.Equals(d.Key, "Runs after", StringComparison.OrdinalIgnoreCase))
                .ToList();

            var simple = details.Where(d => d.Value != null && d.Value.IndexOf('\n') < 0).ToList();
            var blocks = details.Where(d => d.Value != null && d.Value.IndexOf('\n') >= 0).ToList();

            foreach (var kv in simple)
            {
                var value = kv.Value.StartsWith("@") ? "`" + kv.Value + "`" : Clean(kv.Value);
                sb.AppendLine("- **" + Clean(kv.Key) + ":** " + value);
            }
            if (simple.Count > 0) sb.AppendLine();

            // Multi-line values (pretty-printed fetchXml, JSON schemas) go in a
            // fenced block rather than a list item, so the fence stays valid.
            foreach (var kv in blocks)
            {
                sb.AppendLine("**" + Clean(kv.Key) + ":**");
                sb.AppendLine();
                sb.AppendLine("```");
                sb.AppendLine(kv.Value.TrimEnd());
                sb.AppendLine("```");
                sb.AppendLine();
            }
        }

        // ---------- helpers ----------

        private static string Plural(NodeKind kind, int count)
        {
            string word;
            switch (kind)
            {
                case NodeKind.Condition: word = "condition"; break;
                case NodeKind.Loop: word = "loop"; break;
                case NodeKind.Switch: word = "switch"; break;
                case NodeKind.Case: word = "switch case"; break;
                case NodeKind.Empty: word = "empty branch"; break;
                case NodeKind.Trigger: word = "trigger"; break;
                case NodeKind.Terminate: word = "terminate step"; break;
                case NodeKind.Note: word = "note"; break;
                default: word = "action"; break;
            }
            if (count == 1) return word;
            return word.EndsWith("h") ? word + "es" : word + "s";
        }

        private static string JoinWithAnd(List<string> parts)
        {
            if (parts.Count == 0) return "";
            if (parts.Count == 1) return parts[0];
            return string.Join(", ", parts.Take(parts.Count - 1)) + " and " + parts.Last();
        }

        private static string JoinWithAnd(IEnumerable<string> parts) => JoinWithAnd(parts.ToList());

        /// <summary>
        /// Flattens newlines and neutralises the two characters that would start
        /// Markdown syntax mid-sentence.
        ///
        /// Underscores are deliberately NOT escaped. Dataverse is full of names
        /// like jn_status and shared_commondataserviceforapps, and writing them
        /// as jn\_status would mean the indexed text no longer matches what
        /// anyone searches for — which defeats the point of this export. A stray
        /// italic is a much smaller price than an unsearchable logical name.
        /// </summary>
        private static string Clean(string s)
        {
            if (string.IsNullOrEmpty(s)) return "";
            s = s.Replace("\r\n", " ").Replace('\n', ' ').Replace('\r', ' ').Trim();
            return s.Replace("|", "\\|").Replace("*", "\\*");
        }
    }
}
