using System.Globalization;
using System.IO;
using System.Net;
using System.Text;
using DataverseProcessMapper.Rendering;

namespace DataverseProcessMapper.Exporters
{
    /// <summary>
    /// Exports a process map to a standalone SVG file. Visio opens the file as
    /// editable vector shapes; Mural, Lucidchart, draw.io, Figma and browsers
    /// accept it as an import/embed.
    /// </summary>
    public static class SvgExporter
    {
        public static void Save(ProcessMap map, string path)
        {
            // Same page framing as the PDF export: an 8-unit margin all round.
            float w = map.CanvasSize.Width + 16;
            float h = map.CanvasSize.Height + 16;

            string elements;
            using (var surface = new SvgDiagramSurface())
            {
                DiagramRenderer.Render(surface, map.Graph, map.CanvasSize);
                elements = surface.GetElements();
            }

            var sb = new StringBuilder();
            sb.AppendLine("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
            sb.Append("<svg xmlns=\"http://www.w3.org/2000/svg\"")
              .Append(" width=\"").Append(F(w)).Append("\"")
              .Append(" height=\"").Append(F(h)).Append("\"")
              .Append(" viewBox=\"0 0 ").Append(F(w)).Append(' ').Append(F(h)).AppendLine("\">");
            sb.Append("<title>").Append(E(map.Graph.Title ?? "Process Map")).AppendLine("</title>");
            sb.AppendLine("<desc>Generated by Dataverse Process Mapper for XrmToolBox.</desc>");
            sb.Append("<rect width=\"").Append(F(w)).Append("\" height=\"").Append(F(h))
              .AppendLine("\" fill=\"#FFFFFF\"/>");
            sb.AppendLine("<g transform=\"translate(8,8)\">");
            sb.Append(elements);
            sb.AppendLine("</g>");
            sb.AppendLine("</svg>");

            File.WriteAllText(path, sb.ToString(), Encoding.UTF8);
        }

        private static string F(float v) => v.ToString("0.##", CultureInfo.InvariantCulture);

        private static string E(string s) => string.IsNullOrEmpty(s) ? "" : WebUtility.HtmlEncode(s);
    }
}
